//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : IceBlock.java
//  @ Date : 2020. 03. 16.
//  @ Author : 
//
//




public abstract class IceBlock
{
    private int amountOfSnow;
    private int stability;
    private Character characters: Character;
    private Character characters: Character;
    private Item item: Item;
    public void SetNeighbour(Direction d, IceBlock block)
    {
    }
    
    public int GetSnow()
    {
    }
    
    public int GetStability()
    {
    }
    
    public void ChangeAmountOfSnow(int i)
    {
    }
    
    public abstract void Accept(Character c);
    
    public abstract void Remove(Character c);
    
    public Item RemoveItem()
    {
    }
    
    public bool PlaceIgloo()
    {
    }
    
    public bool HasIgloo()
    {
    }
    
    public Character[] GetCharacters()
    {
    }
}
