//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : StableBlock.java
//  @ Date : 2020. 03. 16.
//  @ Author : 
//
//




public class StableBlock extends IceBlock
{
    private bool hasIgloo;
    public void Accept(Character c)
    {
    }
    
    public void Remove(Character c)
    {
    }
    
    public bool PlaceIgloo()
    {
    }
    
    public bool HasIgloo()
    {
    }
    
    public void Accept(Character c)
    {
    }
    
    public void Remove(Character c)
    {
    }
}
