//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Bullet.java
//  @ Date : 2020. 03. 16.
//  @ Author : 
//
//




public class Bullet implements Item
{
    public void Use(IceBlock block)
    {
    }
    
    public Item PickedUp(Character c)
    {
    }
    
    public void Use(IceBlock block);
    
    public Item PickedUp(Character c);
}
