//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Character.java
//  @ Date : 2020. 03. 16.
//  @ Author : 
//
//




public abstract class Character
{
    private int energy;
    private int health;
    private bool isInWater;
    private bool hasSuit;
    private bool hasFlare;
    private bool hasBullet;
    private IceBlock block: IceBlock;
    private Item inventory: Item;
    
    public void Move(Direction d)
    {
    }
    
    public void Clear()
    {
    }
    
    public void PickUp()
    {
    }
    
    public void FallIn()
    {
    }
    
    public abstract void UseAbility();
    
    public void SetHasSuit()
    {
    }
    
    public bool IsDrowning()
    {
    }
    
    public void UseItem()
    {
    }
    
    public abstract void ChangeHealth(int value);
    
    public int GetHealth()
    {
    }
    
    public bool HasFlare()
    {
    }
    
    public void SetHasFlare()
    {
    }
    
    public bool HasBullet()
    {
    }
    
    public void SetHasBullet()
    {
    }
}
