//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : EmptyBlock.java
//  @ Date : 2020. 03. 16.
//  @ Author : 
//
//




public class EmptyBlock extends IceBlock
{
    public void Accept(Character c)
    {
    }
    
    public void Remove(Character c)
    {
    }
    
    public void Accept(Character c)
    {
    }
    
    public void Remove(Character c)
    {
    }
}
