//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Explorer.java
//  @ Date : 2020. 03. 16.
//  @ Author : 
//
//




public class Explorer extends Character
{
    public void UseAbility()
    {
    }
    
    private int CheckStability(Direction d)
    {
    }
    
    public void ChangeHealth(int value)
    {
    }
    
    public void UseAbility()
    {
    }
    
    public void ChangeHealth(int value)
    {
    }
}
