//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Game.java
//  @ Date : 2020. 03. 16.
//  @ Author : 
//
//




public class Game
{
    private bool isWin;
    private bool isLost;
    private IceMap map: IceMap;
    private Character characters: Character;
    private Character currentlyMovingCharacter: Character;
    public void NextRound()
    {
    }
    
    public void Win()
    {
    }
    
    public void Lose()
    {
    }
    
    private void SnowStorm()
    {
    }
}
