//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : IceMap.java
//  @ Date : 2020. 03. 16.
//  @ Author : 
//
//




public class IceMap
{
    private IceBlock blocks: IceBlock;
    public void SetNeighboursOnTheMap()
    {
    }
    
    public IceBlock[] GetBlocks()
    {
    }
}
