//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Item.java
//  @ Date : 2020. 03. 16.
//  @ Author : 
//
//




public interface Item
{
    public void Use(IceBlock block);
    public Item PickedUp(Character c);
}
